### ISSUE TITLE
[BUG] Post List error in 1.0.4

### ISSUE THREAD

**Issue by jjsanderson** [bigbite/benenson#152]
**Describe the bug**
The Post List block doesn't work for me in the Wordpress editor – shows a 'This block has encountered an error and cannot be previewed' message

**To Reproduce**
Steps to reproduce the behaviour:
1. Clean Wordpress 5.2.1 install (via [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) )
2. Install Benenson-1.0.4 release
3. Make a new page, add 'Benenson->Post List' block

**Expected behaviour**
Post List block behaves as expected

**Developer console output (if applicable):**
Throws a Javascript error "Attempted to assign to readonly property" from deep in blocks.js 'in the <t> component.'

**Platform (please complete the following information):**
 - Mac OS X 10.14.4
 - Safari, Chrome

**Additional context**
I hate that my first contribution here is a bug report; I'm liking the theme very much, and the 'doing this for a client and in public' approach is refreshing.

**Comment by jjsanderson** [comment]
Can now confirm that this has been resolved for me in current master.

**Comment by jonmcp** [comment]
Hi @jjsanderson 
Apologies for the slow movement on your report, and thank you for your kind comments. 
A new release should be forthcoming which, thanks to your follow-up, we know should resolve this.
Many thanks

**Comment by jonmcp** [comment]
Hey @jjsanderson 
I've just released [v1.1.0](https://github.com/bigbite/benenson/releases/tag/v1.1.0), which should resolve this.
Thanks again for your report!
